language: node_js
node_js:
  - "10"

install:
  npm install

build:
  npm run build

cache:
  directories:
  - node_modules

branches:
  only:
  - master

script:
  - npm test

after_success:
  - npm run coveralls